[tool.poetry]
name = "psycop_feature_generation"
version = "0.2.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = ">=3.9, <3.11"
numpy = ">=1.2.3, <1.2.4"
scipy = ">=1.8.0, <1.8.1"
pandas = ">=1.4.0, <1.4.1"
catalogue = ">=2.0.0, <2.0.1"
wasabi = ">=0.9.1, <0.9.2"
scikit-learn = ">=1.1.2, <1.1.3"
wandb = ">=0.12.0, <0.13.4"
deepchecks = ">=0.8.0, <0.9.0"
psutil = ">=5.0.0, <5.0.1"
dill = ">=0.3.5, <0.3.6"
pydantic = ">=1.9.0, <1.9.1"
srsly = ">=2.4.4, <2.4.5"
psycopmlutils = {git = "https://github.com/Aarhus-Psychiatry-Research/psycop-ml-utils.git", rev = "main"}
dask = ">=2022.1.1, <2022.1.2"
SQLAlchemy = ">=1.4.41, <1.4.42"
pyodbc = ">=4.0.34, <4.0.35"

[tool.poetry.dev-dependencies]
pytest = ">=7.1.3, <7.1.4"
black = ">=22.8.0, <22.8.1"
pre-commit = ">=2.20.0, <2.20.1"
pytest-cov = ">=3.0.0, <3.0.1"
flake8 = ">=5.0.0, <5.0.5"
docformatter = ">=1.5.0, <1.5.1"
mypy = ">=0.971, <0.972"
pytest-xdist = ">=2.4.0, <2.5.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
known_third_party = ["wandb"]

[tool.pylint]
load-plugins = "pylint.extensions.docparams,pylint.extensions.code_style,pylint.extensions.for_any_all,pylint.extensions.typing"
good-names = "df,p,f,d,e,n,k,i,v"
disable = "too-many-lines,line-too-long,missing-raises-doc,no-self-argument,unused-wildcard-import,wildcard-import,no-else-return,too-many-arguments,redefined-outer-name"

[tool.pyright] # Added because of weird pylance error, issue here: https://github.com/microsoft/pylance-release/issues/3366
