bringing up nodes...
bringing up nodes...

..............F
=================================== FAILURES ===================================
_____________________________ test_plot_bar_chart ______________________________
[gw7] darwin -- Python 3.9.16 /Users/au484925/Desktop/psycop-model-training/.venv/bin/python

synth_eval_dataset = EvalDataset(ids=0        23143
1        23143
2        28277
3        48336
4        48336
         ...  
99995    437.....
99995     6
99996     1
99997    16
99998     5
99999    13
Name: eval_n_hbac1_count, Length: 100000, dtype: int64})

    def test_plot_bar_chart(synth_eval_dataset: EvalDataset):
>       plot_df = create_sensitivity_by_time_to_outcome_df(
            labels=synth_eval_dataset.y,
            y_hat_probs=synth_eval_dataset.y_hat_probs,
            outcome_timestamps=synth_eval_dataset.outcome_timestamps,
            prediction_timestamps=synth_eval_dataset.pred_timestamps,
            positive_rate=0.5,
        )
E       TypeError: create_sensitivity_by_time_to_outcome_df() got an unexpected keyword argument 'labels'

tests/test_model_eval/test_visualizations.py:75: TypeError
=========================== short test summary info ============================
FAILED tests/test_model_eval/test_visualizations.py::test_plot_bar_chart - Ty...
!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!! xdist.dsession.Interrupted: stopping after 1 failures !!!!!!!!!!!!!
1 failed, 14 passed, 1 warning in 14.21s
